import Head from "next/head";

export default function Test() {
  return (
    <div>
      <Head>
        <title>Styled Test Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Test Page</h1>
      </main>
    </div>
  );
}
